[tool.poetry]
name = "valenspy"
version = "0.1.0"
description = "A Python package to validate gridded model data."
authors = ["Your Name <you@example.com>"]
license = ","
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
xarray = "^2024.2.0"
dask = "^2024.3.1"
netCDF4 = "^1.6.5"

[tool.poetry.group.dev.dependencies]
poetry = "^1.8.2"
Sphinx = "^7.2.6"
pre-commit = "^3.6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
