name: Build and deploy documentation

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - documentation

jobs:
#---- Deploy documentation MAIN-----#
  deploy_doc_main:
    name: Deploy main documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.11'
          activate-environment: valenspy_env
          auto-update-conda: true
          auto-activate-base: false
      - name: Create and activate conda environment
        run: |
            conda create -n valenspy_env python=3.11 esmpy poetry=1.8 pytest -c conda-forge -y
            conda activate valenspy_env
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: install pandoc (system wide)
        run: |
          sudo apt-get -y install pandoc
      - name: remove previous builds
        run: |
          rm -f dist/metobs_toolkit-*.whl
          rm -f dist/metobs_toolkit-*.tar.gz
      - name: Install dependencies and build
        run: |
          poetry install --with dev --with docs
          poetry run sphinx-build -a -E docs _build
      - name: deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
