#Create a workflow which runs the tests in the tests folder on push

name: Pytests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
              pip install poetry
              poetry update
              poetry install --with dev
      - name: Run tests
        run: |
          pytest tests/push_tests/test_*.py